version: "3.9"

services:
  db-mongo:
    container_name: db-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"

  front-ng-v1:
    container_name: front-ng-v1
    build:
      context: ./front-ng-v1
      dockerfile: Dockerfile-prod
    volumes:
      - './front-ng-v1:/app'
      - '/app/node_modules'
    ports:
      - '81:80'

  back-node-v1:
    container_name: back-node-v1
    # image: latest123/login-app
    restart: always
    build:
      context: ./back-node-v1
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    links:
      - db-mongo
